name: Deploy to EC2

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node Js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.0'

      - name: Install Dependencies
        run: npm install --frozen-lockfile

      - name: Build App
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh "$EC2_USER@$EC2_HOST" "mkdir -p ~/app"

          rsync -avz \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.github' \
            ./ "$EC2_USER@$EC2_HOST:~/app/"

          # Install Node.js 20.x if missing
          ssh "$EC2_USER@$EC2_HOST" "
            if ! command -v node >/dev/null 2>&1 || ! node -v | grep 'v20.12.0' >/dev/null 2>&1; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
          "

          # Install PM2 globally if missing
          ssh "$EC2_USER@$EC2_HOST" "
            if ! command -v pm2 >/dev/null 2>&1; then
              sudo npm install -g pm2
            fi
          "

          # Install dependencies and build on EC2
          ssh "$EC2_USER@$EC2_HOST" "
            cd ~/app
            npm install --frozen-lockfile
            npm run build
          "

          # Stop existing PM2 process if exists
          ssh "$EC2_USER@$EC2_HOST" "
            pm2 delete nodejs-app || true
          "

          # Start app with PM2 (using built JavaScript file)
          ssh "$EC2_USER@$EC2_HOST" "
            cd ~/app
            pm2 start ./dist/server.js --name nodejs-app
          "
